CREATE DATABASE group27;
CREATE TABLE IF NOT EXISTS group27.Hospital (
  HId INT,
  HName VARCHAR(45) NULL DEFAULT NULL,
  HType VARCHAR(45) NULL DEFAULT NULL,
  HAddress VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (HId));

CREATE TABLE IF NOT EXISTS group27.Patient (
  PId INT NOT NULL,
  PName VARCHAR(45) NOT NULL,
  PAge INT NULL DEFAULT NULL,
  PAddress VARCHAR(45) NULL DEFAULT NULL,
  PPhone VARCHAR(45) NULL DEFAULT NULL,
  RId INT,
  HId INT,
  PRIMARY KEY (PId));

CREATE TABLE IF NOT EXISTS group27.Doctor (
  DId INT NOT NULL,
  DName VARCHAR(45) NOT NULL,
  Specialization VARCHAR(45) NULL DEFAULT NULL,
  DPhone VARCHAR(45) NULL DEFAULT NULL,
  DAddress VARCHAR(45) NULL DEFAULT NULL,
  DSalary VARCHAR(45) NULL DEFAULT NULL,
  HId INT,
  DepId INT,
  PRIMARY KEY (DId));
  
CREATE TABLE IF NOT EXISTS group27.Medicine (
  MId INT,
  MName VARCHAR(45) NULL DEFAULT NULL,
  MType VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (MId));


CREATE TABLE IF NOT EXISTS group27.Department (
  DepId INT,
  DepName VARCHAR(45) NULL DEFAULT NULL,
  HId INT,
  PRIMARY KEY (DepId));

CREATE TABLE IF NOT EXISTS group27.MedicalRecord (
  RId INT,
  AdmitDate DATE,
  IReport VARCHAR(255) NULL DEFAULT NULL,
  FReport VARCHAR(255) NULL DEFAULT NULL,
  PId INT,
  DId INT,
  PRIMARY KEY (RId));
  
CREATE TABLE IF NOT EXISTS group27.Bill (
  BId INT,
  PId INT,
  DoctorCharge FLOAT NULL DEFAULT NULL,
  TestType VARCHAR(45) NULL DEFAULT NULL,
  TestCharge FLOAT NULL DEFAULT NULL,
  RoomCharge FLOAT NULL DEFAULT NULL,
  Miscellaneous FLOAT NULL DEFAULT NULL,
  Total FLOAT,
  PRIMARY KEY (BId));
  
 CREATE TABLE group27.treats(
   DId INT,
   PId INT,
   Totalcredits INT,
   PRIMARY KEY(DId, PId)
 );
 
 ALTER TABLE group27.treats
  ADD FOREIGN KEY(DId) REFERENCES group27.Doctor (DId) ON DELETE CASCADE,
   ADD FOREIGN KEY(PId) REFERENCES group27.Patient (PId) ON DELETE CASCADE;
   
ALTER TABLE group27.Patient
ADD FOREIGN KEY (RId) REFERENCES group27.MedicalRecord (RId),
ADD FOREIGN KEY (HId) REFERENCES group27.Hospital (HId)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE group27.Doctor
ADD FOREIGN KEY (HId) REFERENCES group27.Hospital (HId),
ADD FOREIGN KEY (DepId) REFERENCES group27.Department (DepId)
ON DELETE CASCADE
ON UPDATE CASCADE;
  
  
ALTER TABLE group27.Department
ADD FOREIGN KEY (HId) REFERENCES group27.Hospital (HId)
ON UPDATE CASCADE;

ALTER TABLE group27.MedicalRecord
ADD FOREIGN KEY (PId) REFERENCES group27.Patient (PId),
ADD FOREIGN KEY (DId) REFERENCES group27.Doctor (DId)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE group27.Bill
ADD FOREIGN KEY (PId) REFERENCES group27.Patient(PId)
ON DELETE CASCADE
ON UPDATE CASCADE;